<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

/***
 * Class User
 * @package App\Models
 * @property integer $id
 * @property string $username
 * @property string $name
 * @property string $email
 * @property string $password
 * @property string $remember_token
 */
class User extends Authenticatable
{
    use HasFactory, Notifiable;

    protected $fillable = [
        'username',
        'name',
        'email',
        'password',
    ];

    public $timestamps = false;

    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function userSetting(){
        return $this->hasOne(UserSetting::class);
    }

    public function save(array $options = [])
    {
        $user = parent::save($options); // TODO: Change the autogenerated stub

       $userSetting = $this->userSetting()->first();

       if(empty($userSetting)){
           $userSetting = new UserSetting();
           $userSetting->user_id = $this->id;
           $userSetting->save();
       }

        return $user && $userSetting;
    }
}
